version: "3.0"

services:
  websocket-stt:
    build:
      context: .
    container_name: websocket-stt
    environment:
      WORKERS_PER_CORE: 1.0
      loglevel: DEBUG
    volumes:
      - "./app:/app"
      - "./huggingface:/root/.cache/huggingface"
    ports:
      - "9091:9091"