version: "3.3"

services:
  gradio-f5-tts:
    build:
      context: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["2"]
              capabilities: [gpu]
    container_name: gradio-f5-tts
    ports:
      - "7860:7860"
    volumes:
      - "~/.cache/huggingface:/root/.cache/huggingface"
    environment:
      - HOTLOAD=true
    command: gradio app.py